# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DeactivateActiveLabels
                                 A QGIS plugin
 on/off layer’s label 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-12-11
        copyright            : (C) 2019 by Carlos Eduardo Cagna
        email                : carlos_cagna@yahoo.com.br
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load DeactivateActiveLabels class from file DeactivateActiveLabels.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .deactivate_active_labels import DeactivateActiveLabels
    return DeactivateActiveLabels(iface)
